export const PROJECTS_GRID_VIEW_TAKE_DATA_PER_PAGE = [6, 9, 12];
export const PROJECTS_GRID_VIEW_TAKE = PROJECTS_GRID_VIEW_TAKE_DATA_PER_PAGE[0];

export const PROJECTS_LIST_VIEW_TAKE_DATA_PER_PAGE = [10, 15, 20];
export const PROJECTS_LIST_VIEW_TAKE = PROJECTS_LIST_VIEW_TAKE_DATA_PER_PAGE[0];
