export const TEAM_MEMBERS_GRID_VIEW_TAKE_DATA_PER_PAGE = [6, 9, 12];
export const TEAM_MEMBERS_GRID_VIEW_TAKE = TEAM_MEMBERS_GRID_VIEW_TAKE_DATA_PER_PAGE[0];

export const TEAM_MEMBERS_LIST_VIEW_TAKE_DATA_PER_PAGE = [10, 15, 20];
export const TEAM_MEMBERS_LIST_VIEW_TAKE = TEAM_MEMBERS_LIST_VIEW_TAKE_DATA_PER_PAGE[0];
