export const MEMBERS_GRID_VIEW_TAKE_DATA_PER_PAGE = [6, 9, 12];
export const MEMBERS_GRID_VIEW_TAKE = MEMBERS_GRID_VIEW_TAKE_DATA_PER_PAGE[0];

export const MEMBERS_LIST_VIEW_TAKE_DATA_PER_PAGE = [10, 15, 20];
export const MEMBERS_LIST_VIEW_TAKE = MEMBERS_LIST_VIEW_TAKE_DATA_PER_PAGE[0];
