export const tasks = [
  {
    id: 'TASK-001',
    title: 'Fix login form validation',
    description: 'Update form validation to handle edge cases and improve error messages for better user experience',
    status: 'In Progress',
    priority: 'High',
    severity: 'Medium',
    project: 'E-commerce Platform',
    assignee: {
      name: 'Sarah Chen',
      avatar: '/placeholder.svg?height=32&width=32',
      initials: 'SC',
    },
    dueDate: '2024-01-25',
    createdDate: '2024-01-20',
    completed: false,
    tags: ['Frontend', 'Validation'],
    attachments: 2,
    comments: 5,
  },
  {
    id: 'TASK-002',
    title: 'Optimize database queries',
    description: 'Improve performance of user dashboard by optimizing SQL queries and adding proper indexing',
    status: 'To Do',
    priority: 'Medium',
    severity: 'Low',
    project: 'User Dashboard',
    assignee: {
      name: 'Mike Johnson',
      avatar: '/placeholder.svg?height=32&width=32',
      initials: 'MJ',
    },
    dueDate: '2024-01-30',
    createdDate: '2024-01-18',
    completed: false,
    tags: ['Backend', 'Performance'],
    attachments: 1,
    comments: 3,
  },
  {
    id: 'TASK-003',
    title: 'Implement dark mode toggle',
    description: 'Add dark mode support across all components and pages with proper theme switching',
    status: 'Done',
    priority: 'Low',
    severity: 'Low',
    project: 'Mobile App Redesign',
    assignee: {
      name: 'Alex Kim',
      avatar: '/placeholder.svg?height=32&width=32',
      initials: 'AK',
    },
    dueDate: '2024-01-22',
    createdDate: '2024-01-15',
    completed: true,
    tags: ['Frontend', 'UI/UX'],
    attachments: 0,
    comments: 8,
  },
  {
    id: 'TASK-004',
    title: 'API security audit',
    description: 'Review and update API endpoints for security vulnerabilities and implement proper authentication',
    status: 'In Review',
    priority: 'Critical',
    severity: 'High',
    project: 'API Integration',
    assignee: {
      name: 'Emma Davis',
      avatar: '/placeholder.svg?height=32&width=32',
      initials: 'ED',
    },
    dueDate: '2024-01-28',
    createdDate: '2024-01-19',
    completed: false,
    tags: ['Security', 'Backend'],
    attachments: 3,
    comments: 12,
  },
  {
    id: 'TASK-005',
    title: 'Mobile responsive fixes',
    description: 'Fix layout issues on mobile devices for checkout flow and improve touch interactions',
    status: 'In Review',
    priority: 'High',
    severity: 'Medium',
    project: 'E-commerce Platform',
    assignee: {
      name: 'John Doe',
      avatar: '/placeholder.svg?height=32&width=32',
      initials: 'JD',
    },
    dueDate: '2024-01-26',
    createdDate: '2024-01-17',
    completed: false,
    tags: ['Frontend', 'Mobile'],
    attachments: 1,
    comments: 7,
  },
  {
    id: 'TASK-006',
    title: 'Update documentation',
    description: 'Update API documentation with new endpoints and examples for better developer experience',
    status: 'To Do',
    priority: 'Low',
    severity: 'Low',
    project: 'API Integration',
    assignee: {
      name: 'Lisa Wang',
      avatar: '/placeholder.svg?height=32&width=32',
      initials: 'LW',
    },
    dueDate: '2024-02-05',
    createdDate: '2024-01-21',
    completed: false,
    tags: ['Documentation'],
    attachments: 0,
    comments: 2,
  },
];

export const columns = [
  { id: 'To Do', title: 'To Do', color: 'gray', count: tasks.filter((t) => t.status === 'To Do').length },
  {
    id: 'In Progress',
    title: 'In Progress',
    color: 'blue',
    count: tasks.filter((t) => t.status === 'In Progress').length,
  },
  { id: 'In Review', title: 'In Review', color: 'yellow', count: tasks.filter((t) => t.status === 'In Review').length },
  { id: 'Done', title: 'Done', color: 'green', count: tasks.filter((t) => t.status === 'Done').length },
];
